// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbemFrCqZ0gCA4W6HwNLF47a-JbLU5DJo',
    appId: '1:808525724166:web:f07b1a727773364ae32187',
    messagingSenderId: '808525724166',
    projectId: 'maptest02-9410b',
    authDomain: 'maptest02-9410b.firebaseapp.com',
    storageBucket: 'maptest02-9410b.appspot.com',
    measurementId: 'G-59KPYEH47M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOBmpou1HafvRT-lh4j0812RHBV4zwioA',
    appId: '1:808525724166:android:afb12ede409f23aae32187',
    messagingSenderId: '808525724166',
    projectId: 'maptest02-9410b',
    storageBucket: 'maptest02-9410b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOJ--UylnywkDWPg7xdsvLaZY5Bu7IQ6M',
    appId: '1:808525724166:ios:db3124d3fecf9811e32187',
    messagingSenderId: '808525724166',
    projectId: 'maptest02-9410b',
    storageBucket: 'maptest02-9410b.appspot.com',
    iosClientId: '808525724166-7tf0fibod8ho983i78racj2lb3g0h8mk.apps.googleusercontent.com',
    iosBundleId: 'com.test.maptest.maptest02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOJ--UylnywkDWPg7xdsvLaZY5Bu7IQ6M',
    appId: '1:808525724166:ios:db3124d3fecf9811e32187',
    messagingSenderId: '808525724166',
    projectId: 'maptest02-9410b',
    storageBucket: 'maptest02-9410b.appspot.com',
    iosClientId: '808525724166-7tf0fibod8ho983i78racj2lb3g0h8mk.apps.googleusercontent.com',
    iosBundleId: 'com.test.maptest.maptest02',
  );
}
